Feature territory
eferos93/quentin-sdm-exam pull request #23
Opened 2021-01-11 17:49 UTC by wilsonjefferson

This branch is refereed to `Board` class, you can find some methods to find _regions_ and _territories_. This branch was forked by Exception branch.

2021-01-12 07:50 UTC, stefanosimonetto approved these changes

2021-01-12 09:25 UTC, demirbilek95 requested changes
I think we need some refactoring here, we can talk the details with call

2021-01-12 09:25 UTC, demirbilek95 commented on src/main/java/sdmExam/Board.java
> +            Intersection intersection = new Intersection(Position.in(3, col), Stone.NONE);
Why do we have 3 as hard coded here? (In Position.in(3, col)). Are we looking for territories only in row 3?

2021-01-12 09:25 UTC, demirbilek95 commented on src/main/java/sdmExam/Board.java
> +            if (!intersections.get(i).isOccupied() && findIntersectionInRegions(regions, intersections.get(i))) {
intersections.get(i).isOccupied() is tending to code smell, we may need to find another way to perform

2021-01-16 15:21 UTC, closed without merging

2021-01-16 15:22 UTC, eferos93 commented
Closed until the feature is not implemented properly